export const HEADER_NAMES = Object.freeze({
  authorization: "authorization",
  cfConnectingIp: "cf-connecting-ip",
  cfConnectingIpv6: "cf-connecting-ipv6",
  cfContainerTargetPort: "cf-container-target-port",
  cfIpCountry: "cf-ipcountry",
  cfPseudoIpv4: "cf-pseudo-ipv4",
  cfRay: "cf-ray",
  cfVisitor: "cf-visitor",
  connection: "connection",
  contentLength: "content-length",
  cookie: "cookie",
  forwarded: "forwarded",
  host: "host",
  keepAlive: "keep-alive",
  proxyAuthenticate: "proxy-authenticate",
  proxyAuthorization: "proxy-authorization",
  te: "te",
  trailer: "trailer",
  transferEncoding: "transfer-encoding",
  trueClientIp: "true-client-ip",
  upgrade: "upgrade",
  via: "via",
  xClientIp: "x-client-ip",
  xClusterClientIp: "x-cluster-client-ip",
  xForwardedFor: "x-forwarded-for",
  xForwardedHost: "x-forwarded-host",
  xForwardedPort: "x-forwarded-port",
  xForwardedProto: "x-forwarded-proto",
  xForwardedServer: "x-forwarded-server",
  xRealIp: "x-real-ip",
});

export const PROXY_STRIPPED_REQUEST_HEADERS = Object.freeze([
  HEADER_NAMES.connection,
  HEADER_NAMES.contentLength,
  HEADER_NAMES.cfConnectingIp,
  HEADER_NAMES.cfConnectingIpv6,
  HEADER_NAMES.cfIpCountry,
  HEADER_NAMES.cfPseudoIpv4,
  HEADER_NAMES.cfRay,
  HEADER_NAMES.cfVisitor,
  HEADER_NAMES.forwarded,
  HEADER_NAMES.host,
  HEADER_NAMES.keepAlive,
  HEADER_NAMES.proxyAuthenticate,
  HEADER_NAMES.proxyAuthorization,
  HEADER_NAMES.te,
  HEADER_NAMES.trailer,
  HEADER_NAMES.transferEncoding,
  HEADER_NAMES.trueClientIp,
  HEADER_NAMES.upgrade,
  HEADER_NAMES.via,
  HEADER_NAMES.xClientIp,
  HEADER_NAMES.xClusterClientIp,
  HEADER_NAMES.xForwardedFor,
  HEADER_NAMES.xForwardedHost,
  HEADER_NAMES.xForwardedPort,
  HEADER_NAMES.xForwardedProto,
  HEADER_NAMES.xForwardedServer,
  HEADER_NAMES.xRealIp,
]);
